### ISSUE TITLE
Updating TransformComponents matrix and values (Utilizing properties and dirty flags)

### ISSUE THREAD

**Issue by tlsteenWoo** [JakeHiggins/HorsemenEngine#1]
Request
Working with the engine I quickly ran into issues with TransformComponent not updating its position, rotation, scale variables when it changed the matrix, and also not updating its matrix when changing those same variables. To ensure that m_transform is always update to date I highly recommend taking advantage of properties by setting the fields and additionally setting a boolean flag to update the transform (world matrix). I think this is referred to conceptually as dirty flags. When the property or function for getting the matrix is called it will check if the flag is set, recalculating the matrix, before returning the transform field. If a matrix setter is desired it can set the matrix field directly and perform decomposition immediately to update the other fields, or it can use dirty flags to mark the position,rot,scale for update but thats a bit overkill, I am not requesting a matrix setter here.

pros 
+guarantees everything is up to date
+very efficient
cons
-dependent on proper usage of field and getter/setter to achieve results (internally and externally)

Suggestion
My personal opinion is that the fields should public and be renamed m_translationDirty, m_rotationDirty, m_scaleDirty, and m_transformDirty. This allows for the most flexibility and avoids improper usage by marking these variables dirty, conveying to the user they are involved in dirty flag recalculations. This is how publicizing the RecalculateMatrix method can provide gains.

Steps:
Add a boolean m_transformNeedsUpdate.
Add a public method RecalculateTransform() which updates the transform and set m_transformNeedsUpdate to false
To recalculate the transform the order of operations is identity, translate, rotate, scale. Because it is openGl it is opposite the order you'd do it conceptually except for identity. Identity is mat4() or mat4(1.0).
getTransform() should call updateTransform() if m_transformNeedsUpdate, then return the transform. It's a personal practice that the condition be outside the function. If somebody calls RecalculateTransform it should always recalculate the transform and set the flag to false.
The properties for Position, Rotation, and Scale should get the fields m_translation, m_rotation, and m_scale.
Those same properties should set the fields m_translation, m_rotation, and m_scale and when called should set m_transformNeedsUpdate to false.

Additional:
the method Move(vec3) should not translate the matrix directly as this makes the variable m_Translation out of date. Move can be achieved simply my performing Position += Offset but offering the function is not a bad thing, it's body requires update regardless.

**Comment by tlsteenWoo** [comment]
I was wrong about the position, rotation, scale not being updated. Using the getters updates these by decomposing the matrix. This should be viewed more as a suggestion for allowing matrix to be updated when position, scale, rotation change.

**Comment by JakeHiggins** [comment]
Fixed in 42ca0ec9dfb1a4204bfb1544dab129208249d97a
